# Generated by Django 4.1.6 on 2023-02-12 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingitem',
            old_name='isCompleted',
            new_name='is_completed',
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='shopping_list',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='items_list.shoppinglist'),
            preserve_default=False,
        ),
    ]
