# Generated by Django 4.1.6 on 2023-02-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_list', '0002_rename_iscompleted_shoppingitem_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Shoppin list item description'),
        ),
    ]
