# Generated by Django 4.1.6 on 2023-03-05 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_list', '0005_alter_shoppinglist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='greated_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 5, 9, 57, 30, 720266)),
        ),
    ]
